//import custom labels - lwc48
import saErrorMsg from '@salesforce/label/c.saErrorMsg';import OriginalYearNotInRightFormat from '@salesforce/label/c.OriginalYearNotInRightFormat';
import SelectLegalEntityOrNatural from '@salesforce/label/c.SelectLegalEntityOrNatural';import LimitUnlimitedErrMsg from '@salesforce/label/c.LimitUnlimitedErrMsg';
import FloodWindstormEarthquakeTerrorism from '@salesforce/label/c.FloodWindstormEarthquakeTerrorism';
import NoFileIsFound from '@salesforce/label/c.NoFileIsFound';
import DocumentSavedSuccessMsg from '@salesforce/label/c.DocumentSavedSuccessMsg';
import RequiredFieldMissingSA from '@salesforce/label/c.RequiredFieldMissingSA';
import SAUpdatedSuccessfully from '@salesforce/label/c.SAUpdatedSuccessfully';
import SARenewedSuccessfully from '@salesforce/label/c.SARenewedSuccessfully';
import PlacementTableLoadedSuccessfully from '@salesforce/label/c.PlacementTableLoadedSuccessfully';
import PlacementTableDeletedSuccessfully from '@salesforce/label/c.PlacementTableDeletedSuccessfully';
import EmailNotFound from '@salesforce/label/c.EmailNotFound';
import constantPremiumValue from '@salesforce/label/c.constantPremiumValue';
import powNetPremiumValue from '@salesforce/label/c.powNetPremiumValue';
import ExtensionNotAuthorizedActorCEAXAXL from '@salesforce/label/c.ExtensionNotAuthorizedActorCEAXAXL';
import ExtensionNotAuthorizedAGRE_ActorBasicSalesforceAccess from '@salesforce/label/c.ExtensionNotAuthorizedAGRE_ActorBasicSalesforceAccess';
import ExtensionNotAuthorizedAGRE_ActorBasicSFPlatformAccess from '@salesforce/label/c.ExtensionNotAuthorizedAGRE_ActorBasicSFPlatformAccess';
import ExtensionNotAuthorizedAGRE_Actor_C_E from '@salesforce/label/c.ExtensionNotAuthorizedAGRE_Actor_C_E';
import ExtensionNotAuthorizedAGRECommunityExternalUser from '@salesforce/label/c.ExtensionNotAuthorizedAGRECommunityExternalUser';
import ExtensionNotAuthorizedAGRECommunityInternalUser from '@salesforce/label/c.ExtensionNotAuthorizedAGRECommunityInternalUser';
import ExtensionNotAuthorizedAGRESystemAdmin from '@salesforce/label/c.ExtensionNotAuthorizedAGRESystemAdmin';
import ExtensionNotAuthorizedSystemAdministrator from '@salesforce/label/c.ExtensionNotAuthorizedSystemAdministrator';
import errorMsg from '@salesforce/label/c.errorMsg';


const label = {
    //lwc48 
    saErrorMsg:saErrorMsg,OriginalYearNotInRightFormat:OriginalYearNotInRightFormat,SelectLegalEntityOrNatural:SelectLegalEntityOrNatural,LimitUnlimitedErrMsg:LimitUnlimitedErrMsg,FloodWindstormEarthquakeTerrorism:FloodWindstormEarthquakeTerrorism,NoFileIsFound:NoFileIsFound,DocumentSavedSuccessMsg:DocumentSavedSuccessMsg,RequiredFieldMissingSA:RequiredFieldMissingSA,SAUpdatedSuccessfully:SAUpdatedSuccessfully,SARenewedSuccessfully:SARenewedSuccessfully,PlacementTableLoadedSuccessfully:PlacementTableLoadedSuccessfully,PlacementTableDeletedSuccessfully:PlacementTableDeletedSuccessfully,EmailNotFound:EmailNotFound,errorMsg:errorMsg,constantPremiumValue:constantPremiumValue,powNetPremiumValue:powNetPremiumValue,ExtensionNotAuthorizedActorCEAXAXL:ExtensionNotAuthorizedActorCEAXAXL,ExtensionNotAuthorizedAGRE_ActorBasicSalesforceAccess:ExtensionNotAuthorizedAGRE_ActorBasicSalesforceAccess,ExtensionNotAuthorizedAGRE_ActorBasicSFPlatformAccess:ExtensionNotAuthorizedAGRE_ActorBasicSFPlatformAccess,ExtensionNotAuthorizedAGRE_Actor_C_E:ExtensionNotAuthorizedAGRE_Actor_C_E,ExtensionNotAuthorizedAGRECommunityExternalUser:ExtensionNotAuthorizedAGRECommunityExternalUser,ExtensionNotAuthorizedAGRECommunityInternalUser:ExtensionNotAuthorizedAGRECommunityInternalUser,ExtensionNotAuthorizedAGRESystemAdmin:ExtensionNotAuthorizedAGRESystemAdmin,ExtensionNotAuthorizedSystemAdministrator:ExtensionNotAuthorizedSystemAdministrator,
    fileErrorMsg : 'The total size of documents exceeds 50Mo. Your request cannot be sent. Please review the list of documents..'

};
export {label};